Algoritmo "03_Exercicios_Calcular_Idade"
// Descrição   : Calcular a idade
// Autor(a)    : Antonio Marcos dos Santos de Souza
// Professor   : Adriano Leite da Silva
// Data atual  : 10/02/2021
Var


   nasc, hoje: inteiro

Inicio

   escreval("Digite o ano em que você nasceu: ")
   leia (nasc)
   escreval("digite o ano atual: ")
   leia (hoje)
   limpatela
   escreval ("Atualmente você tem ", hoje - nasc -1, " anos de idade")
   
   
Fimalgoritmo