Algoritmo "24_Enquanto_Nao0 "
// Matéria     : Linguagem e lógica de programação
// Professor   : Adriano Leite da Silva
// Autor(a)    : Antonio Marcos dos Santos de Souza
// Data atual  : 17/02/2021
Var

   num: inteiro


Inicio

     escreva("Digite um número: ")
   leia (num)
   enquanto  num <> 0  faca
      escreva("Digite um número: ")
   leia (num)
   fimenquanto
   escreval("O número 0 foi digitado")

Fimalgoritmo