Algoritmo "27_Repita_Ate0"
// Matéria     : Linguagem e lógica de programação
// Professor   : Adriano Leite da Silva
// Autor(a)    : Antonio Marcos dos Santos de Souza
// Data atual  : 17/02/2021
Var

   i: inteiro


Inicio

    escreva("Digite um número: ")
    leia(i)

   repita
      escreva("Digite um número: ")
    leia(i)
   ate (i = 0)
   escreva("O número 0 foi digitado")
    

Fimalgoritmo